# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/user/repos/pynq_dsp_hw/pynq_dsp_hw/pynq_dsp_hw.srcs/sources_1/bd/base/ip/base_xbar_9/base_xbar_9.xci
# IP: The module: 'base_xbar_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/repos/pynq_dsp_hw/pynq_dsp_hw/pynq_dsp_hw.srcs/sources_1/bd/base/ip/base_xbar_9/base_xbar_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_xbar_9'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/user/repos/pynq_dsp_hw/pynq_dsp_hw/pynq_dsp_hw.srcs/sources_1/bd/base/ip/base_xbar_9/base_xbar_9.xci
# IP: The module: 'base_xbar_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/repos/pynq_dsp_hw/pynq_dsp_hw/pynq_dsp_hw.srcs/sources_1/bd/base/ip/base_xbar_9/base_xbar_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_xbar_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
