create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list base_i/ps7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[0]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[1]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[2]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[3]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[4]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[5]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[6]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[7]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[8]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[9]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[10]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[11]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[12]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[13]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[14]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[15]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[16]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[17]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[18]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[19]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[20]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[21]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[22]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[23]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[24]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[25]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[26]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[27]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[28]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[29]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[30]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_R_reg[31]_0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[0]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[1]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[2]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[3]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[4]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[5]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[6]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[7]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[8]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[9]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[10]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[11]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[12]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[13]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[14]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[15]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[16]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[17]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[18]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[19]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[20]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[21]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[22]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[23]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[24]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[25]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[26]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[27]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[28]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[29]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[30]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataTx_L_reg[31]_0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 24 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[0]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[1]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[2]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[3]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[4]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[5]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[6]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[7]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[8]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[9]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[10]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[11]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[12]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[13]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[14]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[15]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[16]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[17]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[18]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[19]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[20]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[21]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[22]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_R_reg[23]_0[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 24 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[0]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[1]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[2]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[3]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[4]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[5]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[6]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[7]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[8]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[9]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[10]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[11]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[12]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[13]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[14]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[15]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[16]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[17]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[18]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[19]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[20]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[21]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[22]} {base_i/audio_codec_ctrl_0/U0/USER_LOGIC_I/DataRx_L_reg[23]_0[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[0]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[1]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[2]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[3]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[4]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[5]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[6]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[7]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[8]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[9]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[10]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[11]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[12]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[13]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[14]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[15]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[16]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[17]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[18]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[19]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[20]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[21]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[22]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[23]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[24]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[25]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[26]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[27]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[28]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[29]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[30]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_RDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[0]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[1]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[2]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[3]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[4]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[5]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[6]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[7]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[8]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[9]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[10]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[11]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[12]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[13]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[14]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[15]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[16]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[17]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[18]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[19]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[20]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[21]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[22]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[23]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[24]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[25]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[26]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[27]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[28]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[29]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[30]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 7 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_ARADDR[0]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_ARADDR[1]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_ARADDR[2]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_ARADDR[3]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_ARADDR[4]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_ARADDR[5]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_ARADDR[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 30 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[0]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[1]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[2]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[3]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[4]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[5]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[6]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[7]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[8]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[9]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[10]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[11]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[12]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[13]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[14]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[15]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[16]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[17]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[18]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[19]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[20]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[21]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[22]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[23]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[24]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[25]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[26]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[27]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[28]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/int_basePhysAddr_V_reg[31]_0[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 4 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WSTRB[0]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WSTRB[1]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WSTRB[2]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_WSTRB[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 7 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_AWADDR[0]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_AWADDR[1]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_AWADDR[2]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_AWADDR[3]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_AWADDR[4]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_AWADDR[5]} {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/s_axi_AXILiteS_AWADDR[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/lrclk_V[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/ap_start]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list base_i/pynq_dsp_hls_0/inst/pynq_dsp_hls_AXILiteS_s_axi_U/ap_done]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
